[project]
name = "stableswap"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.sip-010-trait-ft-standard]
path = "contracts/external/sip-010-trait-ft-standard.clar"

[contracts.stableswap]
path = "contracts/stableswap.clar"

[contracts.usda-token]
path = "contracts/external/usda-token.clar"

[contracts.xusd-token]
path = "contracts/external/xusd-token.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
